config-version = 2

start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[workspace-to-monitor-force-assignment]
1 = 'built-in'
2 = 'built-in'
3 = 'built-in'
4 = 'built-in'
5 = 'built-in'
6 = ['secondary', 'built-in']
7 = ['secondary', 'built-in']
8 = ['secondary', 'built-in']
9 = ['secondary', 'built-in']
10 = ['secondary', 'built-in']

[mode.main.binding]
alt-enter = 'exec-and-forget open -na "Ghostty"'
alt-shift-enter = 'exec-and-forget open -a "Safari"'
alt-shift-e = 'exec-and-forget open -a "Finder"'
alt-shift-s = 'exec-and-forget open -a "Spotify"'
alt-shift-n = 'exec-and-forget open -a "Visual Studio Code"'
alt-shift-a = 'exec-and-forget open "https://chatgpt.com"'
alt-shift-y = 'exec-and-forget open "https://youtube.com"'
alt-shift-m = 'exec-and-forget open "https://messenger.com"'

alt-q = 'close'
alt-f = 'fullscreen'
alt-t = 'layout floating tiling'
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'
alt-r = 'flatten-workspace-tree'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'swap left'
alt-shift-j = 'swap down'
alt-shift-k = 'swap up'
alt-shift-l = 'swap right'

alt-backslash = 'split horizontal'
alt-minus = 'split vertical'
alt-leftSquareBracket = 'resize smart -50'
alt-rightSquareBracket = 'resize smart +50'
alt-shift-leftSquareBracket = 'resize smart-opposite -50'
alt-shift-rightSquareBracket = 'resize smart-opposite +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'workspace-back-and-forth'
alt-space = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['reload-config', 'mode main']
f = ['layout floating tiling', 'mode main']
b = ['balance-sizes', 'mode main']
w = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
