config-version = 2

start-at-login = false

after-startup-command = [
  'exec-and-forget borders active_color="glow(0xff00ffff)" width=10.0'
]


enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[workspace-to-monitor-force-assignment]
1 = 'built-in'
2 = 'built-in'
3 = 'built-in'
4 = 'built-in'
5 = 'built-in'
6 = ['secondary', 'built-in']
7 = ['secondary', 'built-in']
8 = ['secondary', 'built-in']
9 = ['secondary', 'built-in']
10 = ['secondary', 'built-in']

[mode.main.binding]
cmd-h = []
cmd-tab = 'focus --boundaries-action wrap-around-the-workspace dfs-next'
cmd-shift-tab = 'focus --boundaries-action wrap-around-the-workspace dfs-prev'

alt-enter = 'exec-and-forget open -na "Ghostty"'

ctrl-q = 'close'
ctrl-f = 'fullscreen'
ctrl-t = 'layout floating tiling'
ctrl-p = 'layout tiles accordion'
ctrl-slash = 'layout tiles horizontal vertical'
ctrl-comma = 'layout accordion horizontal vertical'
ctrl-r = 'flatten-workspace-tree'

ctrl-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
ctrl-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
ctrl-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
ctrl-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-backslash = 'split horizontal'
ctrl-minus = 'split vertical'
ctrl-leftSquareBracket = 'resize smart -50'
ctrl-rightSquareBracket = 'resize smart +50'
ctrl-shift-leftSquareBracket = 'resize smart-opposite -50'
ctrl-shift-rightSquareBracket = 'resize smart-opposite +50'

ctrl-1 = 'workspace 1'
ctrl-2 = 'workspace 2'
ctrl-3 = 'workspace 3'
ctrl-4 = 'workspace 4'
ctrl-5 = 'workspace 5'
ctrl-6 = 'workspace 6'
ctrl-7 = 'workspace 7'
ctrl-8 = 'workspace 8'
ctrl-9 = 'workspace 9'
ctrl-0 = 'workspace 10'

ctrl-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-2 = 'move-node-to-workspace 2'
ctrl-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-4 = 'move-node-to-workspace 4'
ctrl-shift-5 = 'move-node-to-workspace 5'
ctrl-shift-6 = 'move-node-to-workspace 6'
ctrl-shift-7 = 'move-node-to-workspace 7'
ctrl-shift-8 = 'move-node-to-workspace 8'
ctrl-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'focus --boundaries-action wrap-around-the-workspace dfs-next'
alt-shift-tab = 'focus --boundaries-action wrap-around-the-workspace dfs-prev'
alt-space = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['reload-config', 'mode main']
f = ['layout floating tiling', 'mode main']
b = ['balance-sizes', 'mode main']
w = ['flatten-workspace-tree', 'mode main']
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
